[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.05.01
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=Version: 	v1_0\\Programmer: SPM\\Comments:	Initial Release\\\\Intructions:
  Cmn2=\\This module is used to manage the power and input control for||1
  Cmn3=devices (eg. tv, avr, etc). It has a max of\\10 inputs (can be changed||1
  Cmn4=in the code) and a progress range of 0-100 (ie. use this range on||1
  Cmn5=the gauge).\\      \\// Inputs\\\\Digital:\\PowerOn 						- Power||1
  Cmn6=on device\\PowerOff						- Power off device\\Input[n]						- Select||1
  Cmn7=device input. Also switches on power if device is off. Max = 10||1
  Cmn8=||f	\\\\||5
  Cmn9=||1\\// Outputs\\\\Digital:\\PowerOnOut						- Power on signal to||1
  Cmn10=be linked with device power on command \\PowerOffOut						- Power||1
  Cmn11=off signal to be linked with device power of command \\InputOut[n]	
  Cmn12=					- Power on signal to be linked with device power on command.
  Cmn13=||1Max = 10\\progressFb						- digital indication that progress is||1
  Cmn14=busy. Can be tied to a popup.\\\\Analog:\\progress#						- Value||1
  Cmn15=from 0-100 to show progress from when device is powered up to \\
  Cmn16=								  when it is ready to accept commands. \\\\\\   (add additional||1
  Cmn17=lines of help lines)
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,362,378,380,405,407,408,409,478,522,537,554,586,590,611,624,718,756,767,830,841,842,854,883,955,1032,1062,1079,1128,1129,1134,1140,1157,1158,1195,1199,1220,1221,1222,1223,1299,1348,1349,1439,1472,1473,1499,1746,1803,1975,2229,2354,2514,2523,2532,2706,2707,3235,3236,3427,3454,3567,3568,3601,3602,3708,3902,3903,3912,3918,3925,3926,4206,4207,
  Exclusions_CDS=5
  Inclusions_CDS=6,7
  Name=proAv_DvCtrl
  SmplCName=proAv_DvCtrl.usp
  Code=1
  SysRev5=4.000
  SMWRev=2.02.05
  InputCue1=[~UNUSED~]
  InputSigType1=Digital
  InputCue2=PowerOn
  InputSigType2=Digital
  InputCue3=PowerOff
  InputSigType3=Digital
  InputCue4=[~UNUSED~]
  InputSigType4=Digital
  InputCue5=resetProgress
  InputSigType5=Digital
  InputCue6=[~UNUSED~]
  InputSigType6=Digital
  InputCue7=Input[#]
  InputSigType7=Digital
  OutputCue1=[~UNUSED~]
  OutputSigType1=Digital
  OutputCue2=PowerOnOut
  OutputSigType2=Digital
  OutputCue3=PowerOffOut
  OutputSigType3=Digital
  OutputCue4=[~UNUSED~]
  OutputSigType4=Digital
  OutputCue5=progressFb
  OutputSigType5=Digital
  OutputCue6=[~UNUSED~]
  OutputSigType6=Digital
  OutputCue7=InputOut[#]
  OutputSigType7=Digital
  OutputList2Cue1=[~UNUSED~]
  OutputList2SigType1=Analog
  OutputList2Cue2=progress/#
  OutputList2SigType2=Analog
  ParamCue1=[Reference Name]
  ParamCue2=pwrDelay
  ParamSigType2=Constant
  MinVariableInputs=7
  MaxVariableInputs=16
  MinVariableInputsList2=0
  MaxVariableInputsList2=0
  MinVariableOutputs=7
  MaxVariableOutputs=16
  MinVariableOutputsList2=2
  MaxVariableOutputsList2=2
  MinVariableParams=1
  MaxVariableParams=1
  Expand=expand_inputs_with_outputs
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=32
  Hint=
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  MPp=2
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2_proAv_DvCtrl
  SymJam=NonExclusive
  FileName=proAv_DvCtrl.ush
  SIMPLPlusModuleEncoding=0
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  HD=True
  DV=3d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=0
[END]
